# Generated by Django 4.2.1 on 2023-05-25 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100, unique=True)),
                ('Descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(choices=[('RC', 'REGISTRO CIVIL DE NACIMIENTO'), ('TI', 'TARJETA DE IDENTIDAD'), ('CC', 'CEDULA DE CIUDADANIA'), ('TE', 'TARJETA DE EXTRANJERIA'), ('CE', 'CEDULA DE EXTRANJERIA'), ('NIT', 'NIT'), ('PAS', 'PASAPORTE')], max_length=100, unique=True)),
                ('Descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=100)),
                ('Apellidos', models.CharField(max_length=100)),
                ('Documento', models.CharField(max_length=50)),
                ('FechaNacimiento', models.DateField()),
                ('Email', models.CharField(max_length=100)),
                ('Telefono', models.CharField(max_length=50)),
                ('Usuario', models.CharField(max_length=50)),
                ('Contraseña', models.CharField(max_length=100)),
                ('IdTipoDocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Index.tipodocumento')),
                ('LugarResidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Index.ciudad')),
            ],
        ),
    ]
